### ISSUE TITLE
Chebyshev net

### ISSUE THREAD

**Issue by petrasvestartas** [pearswj/buckminster#18]
Hi,

I saw the implementation of Chebyshev net in C# from:
http://graphicon.ru/html/2002/pdf/Popov_En_Re.pdf
on:
https://vimeo.com/71686437

Is the code available or possible to try?:)

**Comment by pearswj** [comment]
See [Buckminster/Components/ChebychevComponent.cs](../blob/master/Buckminster/Components/ChebychevComponent.cs)
