### ISSUE TITLE
Chebyshev nets

### ISSUE THREAD

**Issue by petrasvestartas** [pearswj/buckminster#19]
How normally naked edges are computed for chebyshev nets?

Are the last segments extended somehow?

And the part at the corners  after 45 degree rotation, when segments do not reach corner.
Why this happens?

![output_6ome4p](https://user-images.githubusercontent.com/18013985/31376023-c3bdcd30-ada3-11e7-9562-78e7dbebada0.gif)

**Comment by petrasvestartas** [comment]
I do not know if it is good method, but on extended surface, I checked mesh face vertices.
If they are close to surface within 0.001 tolerance, I keep faces, if not  I do something like this:

<img width="568" alt="mesh" src="https://user-images.githubusercontent.com/18013985/31427443-93c74100-ae67-11e7-93e3-9f07b2fd5214.png">


Point3d[] facePt = new Point3d[] { quad[i, j] , quad[i - 1, j] , quad[i - 1, j - 1] , quad[i, j - 1] };

                                        Sold.ClosestPoint(quad[i, j], out double u1, out double v1);
                                        Sold.ClosestPoint(quad[i - 1, j], out double u2, out double v2);
                                        Sold.ClosestPoint(quad[i - 1, j - 1], out double u3, out double v3);
                                        Sold.ClosestPoint(quad[i, j - 1], out double u4, out double v4);

                                        double tolerance = 0.0001;
                                        bool[] flag = new bool[] {
                                        Sold.PointAt(u1, v1).DistanceTo(quad[i, j]) < tolerance,
                                        Sold.PointAt(u2, v2).DistanceTo(quad[i - 1, j]) < tolerance,
                                        Sold.PointAt(u3, v3).DistanceTo(quad[i - 1, j - 1]) < tolerance,
                                        Sold.PointAt(u4, v4).DistanceTo(quad[i, j - 1])< tolerance
                                    };



                                        //Rhino.RhinoApp.WriteLine( d1.ToString() + " " + d2.ToString() + " " + d3.ToString() + " " + d4.ToString());


                                        if (flag[0] && flag[1] && flag[2] && flag[3]) {
                                            qmesh.Faces.AddFace(qindex[i, j], qindex[i - 1, j], qindex[i - 1, j - 1], qindex[i, j - 1]);// create quad-face
                                        } else if (flag[0] || flag[1] || flag[2] || flag[3]) {

                                            Polyline temp = new Polyline();

                                            for (int p = 0; p < 4; p++) {


                                                switch (Convert.ToInt32(flag[p]) * 10 + Convert.ToInt32(flag[(p+1)%4])) {

                                                    case (11):
                                                    temp.Add(facePt[p]);
                                                    break;
                                                    case (10):
                                                    temp.Add(facePt[p]);
                                                    temp.Add(ClosestPointOnNakedEdge(MyNakedEdges, facePt[p], new Line(facePt[p] , facePt[(p + 1) % 4])));
                                                    break;
                                                    case (1):
                                                    temp.Add(ClosestPointOnNakedEdge(MyNakedEdges, facePt[p], new Line(facePt[p], facePt[(p + 1) % 4])));
                                                    break;
                                                    case (0):
                                                    Sold.ClosestPoint(facePt[p],out double u6, out double v6);
                                                    temp.Add(Sold.PointAt(u6,v6));
                                                    break;

                                                }
                                               

                                            }
                                           temp.Close();
                                            polylines.Add(temp);

       

                                            //qmesh.Faces.AddFace(qindex[i, j], qindex[i - 1, j], qindex[i - 1, j - 1], qindex[i, j - 1]);// create quad-face
                                        }

**Comment by petrasvestartas** [comment]
But for rotation I still have no solution. I assume when it is rotated, axis do not extend enough to cover corners?

![rotation](https://user-images.githubusercontent.com/18013985/31427696-6f7b692e-ae68-11e7-92c8-46b601b6db47.jpg)

**Comment by pearswj** [comment]
Hey Petras! I think I remember you mentioning Chebyshev Nets in your DMS talk. It's cool that you're looking at this stuff! The edge trimming looks awesome; Thanks for sharing the code 🙂 

I tried adding some code to extend the mesh beyond the original "axes" in 1b0232c but I think I messed up the implementation... The basic idea is that, for any given column (or row) of edges, you can use the direction of the last edge to do another surface/arc intersection (essentially, the same method used to create the original axes). Then you can use the new point to continue the surface/sphere/sphere intersections.

![screen shot 2017-10-11 at 10 29 50](https://user-images.githubusercontent.com/121068/31432739-36c204ec-ae6f-11e7-8bd6-9f9513c9fb4d.png)

Hope that helps a bit!

**Comment by petrasvestartas** [comment]
Hi,

Thank for this extension bit, I will try to implement it.

I also know you from AAG preworkshop at CITA and plankton is a great help for me.

What do you think takes the longest time to calculate meshing is it intersection between surface / arc-sphere?
